### ISSUE TITLE
Not ending the scrobble

### ISSUE THREAD

**Issue by vensauro** [flaree/lastfm-red#12]
when playing, on lastfm shows that are scrobbling the music, but when the music ends, the music not appear on the lastfm.

**Comment by vensauro** [comment]
Have a way to me help debug this? i don't know how to modifier the code and test

**Comment by tigattack** [comment]
This sounds like a Last.FM issue, rather than an issue with this cog.

**Comment by ryan5453** [comment]
@vensauro this is happening when you play music with Red's audio cog, right?

**Comment by vensauro** [comment]
> @vensauro this is happening when you play music with Red's audio cog, right?

yes,  using the audio cog to play musics from yt/music.yt

**Comment by vensauro** [comment]
> This sounds like a Last.FM issue, rather than an issue with this cog.

maybe, but other scrobblers works well, like app scrobbler, or using the fm.bot with some discord bot that has suports

**Comment by ryan5453** [comment]
> > This sounds like a Last.FM issue, rather than an issue with this cog.
> 
> maybe, but other scrobblers works well, like app scrobbler, or using the fm.bot with some discord bot that has suports

I am aware of this issue and I haven't found a way to fix it yet without messing up a bunch of other stuff. I'll look into it a little more soon.

**Comment by ryan5453** [comment]
@vensauro I am closing this as it should be fixed in the latest release, but feel free to reopen it if you're still running into this issue.
